### ISSUE TITLE
sendText,sendBinary,sendPing mismatched because of AsyncSocket and AsyncWebSocket.

### ISSUE THREAD

**Issue by gogolxdong** [niv/websocket.nim#40]
I think you might want to unexport the AsyncSocket ones.

**Comment by hlaaftana** [comment]
The AsyncWebSocket procs were just added and the AsyncSocket procs were there since the beginning so I didn't remove them. I also think the AsyncSocket procs should stay for manual socket management, so the one thing I can think of doing is moving them to a seperate module. If this causes any real ambiguities currently though, I'd love to see a reason for that to be done now.

**Comment by gogolxdong** [comment]
wsserver.nim(23, 21) Error: type mismatch: got <AsyncWebSocket, string>
but expected one of:
proc sendText(ws: AsyncWebSocket; p: string; masked: bool): Future[void]
  first type mismatch at position: 3
  required type: bool
proc sendText(ws: AsyncSocket; p: string; masked: bool): Future[void]
  first type mismatch at position: 1
  required type: AsyncSocket
  but expression 'ws' is of type: AsyncWebSocket

expression: sendText(ws, "thanks for the data!")

**Comment by hlaaftana** [comment]
That's because of masked: bool, the signature was changed to `masked: bool = false` only after the current nimble version. I'll update
